### ISSUE TITLE
From where to download ?

### ISSUE THREAD

**Issue by omerjerk** [moto8916/android_device_motorola_merlin#1]
Have you guys released it on xda yet ?
I've Merlin and can build and release on xda if you haven't done yet.
Of course, proper credits will be given.

**Comment by sultanqasim** [comment]
We are working on it. We will release it when it's ready. We are not looking for someone to post our work for us.

**Comment by sultanqasim** [comment]
This does need testing (and possibly fixing) though, as I don't have a merlin device. If you want to help us out, we'd appreciate you testing builds (you make) and providing feedback and/or patches.
